% Dowbnload data4.mat and put it in
% 

% main.m

addpath ../data/lpsdb
addpath solvers
addpath tools
addpath tutorials
fix_paths

%%
data_nr = 3;   % Use example data data_nr
system_nr = 3; % Use system system_nr


%% read a database of benchmark examples
[data]=read_from_lpsdb(systemsettings,3); % Use example data data_nr

%% Choose one or several systems to test.
systems = {...
    'system_misstoa_rand_bundle',...
    'system_misstoa_hack_bundle',...
    'system_misstoa_ransac_bundle',...
    'system_misstoa_rand_wiberg_bundle',...
    'system_misstoa_rand_bundle_l1',...
    'system_misstoa_hack_bundle_l1'...
    };
systemtexts = {...
    'Rand init l_2 opt',...
    'SVD init l_2 opt',...
    'Ransac + l_2 opt',...
    'l_2 opt using Wiberg alg',...
    'rand init + l_1 opt',...
    'SVD init + l_1 opt'...
    };

%%
ii = 3; % Use system 3
[rtmp,stmp,inltmp,res,jac]=feval(systems{ii},data.d);



%% Visualize results

